
namespace Mag.Shared
{
	public enum ObjectClass
	{
		Unknown = 0,
		MeleeWeapon = 1,
		Armor = 2,
		Clothing = 3,
		Jewelry = 4,
		Monster = 5,
		Food = 6,
		Money = 7,
		Misc = 8,
		MissileWeapon = 9,
		Container = 10,
		Gem = 11,
		SpellComponent = 12,
		Key = 13,
		Portal = 14,
		TradeNote = 15,
		ManaStone = 16,
		Plant = 17,
		BaseCooking = 18,
		BaseAlchemy = 19,
		BaseFletching = 20,
		CraftedCooking = 21,
		CraftedAlchemy = 22,
		CraftedFletching = 23,
		Player = 24,
		Vendor = 25,
		Door = 26,
		Corpse = 27,
		Lifestone = 28,
		HealingKit = 29,
		Lockpick = 30,
		WandStaffOrb = 31,
		Bundle = 32,
		Book = 33,
		Journal = 34,
		Sign = 35,
		Housing = 36,
		Npc = 37,
		Foci = 38,
		Salvage = 39,
		Ust = 40,
		Services = 41,
		Scroll = 42,
		NumObjectClasses = 43,
	}
}
